- job:
    name: grenade-ceilometer
    parent: grenade
    voting: false
    required-projects:
      - opendev.org/openstack/grenade
      - opendev.org/openstack/ceilometer
    vars:
      configure_swap_size: 8192
      grenade_devstack_localrc:
        shared:
          CEILOMETER_BACKEND: gnocchi
      devstack_plugins:
        ceilometer: https://opendev.org/openstack/ceilometer
      devstack_services:
        ceilometer-acompute: true
        ceilometer-acentral: true
        ceilometer-aipmi: true
        ceilometer-anotification: true
    irrelevant-files: &ceilometer-irrelevant-files
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^ceilometer/tests/.*$

- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-xena-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - release-notes-jobs-python3
      - openstack-lower-constraints-jobs
    check:
      jobs:
        - grenade-ceilometer
        - telemetry-dsvm-integration-centos-8s:
            irrelevant-files: *ceilometer-irrelevant-files
        - telemetry-dsvm-integration-centos-8s-fips:
            irrelevant-files: *ceilometer-irrelevant-files
        - telemetry-dsvm-integration:
            irrelevant-files: *ceilometer-irrelevant-files
        - telemetry-dsvm-integration-ipv6-only:
            irrelevant-files: *ceilometer-irrelevant-files
    gate:
      queue: telemetry
      jobs:
        - grenade-ceilometer
        - telemetry-dsvm-integration-centos-8s:
            irrelevant-files: *ceilometer-irrelevant-files
        - telemetry-dsvm-integration-centos-8s-fips:
            irrelevant-files: *ceilometer-irrelevant-files
        - telemetry-dsvm-integration:
            irrelevant-files: *ceilometer-irrelevant-files
        - telemetry-dsvm-integration-ipv6-only:
            irrelevant-files: *ceilometer-irrelevant-files
